local weld = Instance.new("Weld")
local KeyCode = Enum.KeyCode.Insert
----------
local DummyName = ["DUMMY NAME HERE"] --Please ne sure of adding the name of the reanims dummy in here, you can see the name of it with darkdex, just check inside of your Character in workspace.
----------
local player = game.Players.LocalPlayer
local Character = player.Character
local upping = false
local UIS = game:GetService("UserInputService")
local upPos = CFrame.new(-1.45,0.80,0.60)
local upRotation = CFrame.Angles(math.rad(-100),0,0)
local actualPos = CFrame.new(0,0,0)
local actualRot = CFrame.Angles(0,0,0)
local downPos = CFrame.new(1.45,0,0)
local downRot = CFrame.Angles(0,0,0)

UIS.InputBegan:Connect(function(input)
	if input.KeyCode == KeyCode then
		-- Script generated by TurtleSpy, made by Intrer#0421
		upping = true
	end
end)

UIS.InputEnded:Connect(function(input)
	if input.KeyCode == KeyCode then
		upping = false
	end
end)

local Arm = Character["Right Arm"]
local Torso = Character.Torso

weld.Parent = Torso
weld.Part0 = Torso
weld.Part1 = Arm
weld.Name = "NaziHand"

game:GetService("RunService").Stepped:Connect(function()
	if weld.Part1 ~= nil then
		weld.C1 = actualPos*actualRot
	end
	if upping == true then
		weld.Part1 = Arm
		actualPos = actualPos:Lerp(upPos, 0.2)
		actualRot = actualRot:Lerp(upRotation, 0.2)
	else
		weld.Part1 = nil
	end
end)